field: f936530d-29a5-4460-9ccd-b586bfb25329 # Call to actions
fieldLayouts:
  894f6e45-935c-449a-b890-97a1b7730b7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a3573b91-af94-43de-8ceb-dc11cb7175b1 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7de87ca-53a9-4e8e-9c24-53dd6a3a35a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7f7922f-95e3-4540-9c1e-48356f924491
        userCondition: null
fields:
  a3573b91-af94-43de-8ceb-dc11cb7175b1: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkIt
    instructions: null
    name: Link
    searchable: true
    settings:
      allowClass: '1'
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        4: email
        6: url
      class: null
      classes: null
      defaultLinkName: entry
      defaultText: ''
      typeSettings:
        __assoc__:
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
    translationKeyFormat: null
    translationMethod: site
    type: statikbe\cta\fields\CTAField
handle: cta
name: CTA
sortOrder: 1
