fieldLayouts:
  d51eb06b-267f-4376-aeb4-27dd5a7cbd55:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dda3e86c-903d-40c2-bd52-bbc177b59396
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41ff0853-9eda-489f-8241-18d79c37e759
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12aebf15-9f8f-4855-9013-66a176b9e9ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f51144c-2021-41e8-bafa-5f5905e65d65
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b30185b4-c4bb-46ab-ba5c-ade682499148
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 3f19a97a-f123-49f9-a496-940efd348cd4
        userCondition: null
handle: accessibilityStatement
hasTitleField: true
name: 'Accessibility Statement'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
