color: blue
fieldLayouts:
  f997fbbd-3d0f-4ed7-adc1-ba30da763d82:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-27T13:49:58+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8145df63-d12f-47b2-be61-8cc8a8fd6849
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Contentbuilder Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 758a3b32-9080-4bd9-bcf4-94125e1493a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 7d5a93a5-4324-462a-9dad-375cb5172cce # Text - Contentbuilder Body Simple
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7890db9a-85df-4352-9aa0-e84e1856466f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 7def856e-47b3-4b83-ba43-23b5da28a176 # Content Builder - Call To Action - Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05216db1-92ad-4acb-ad4a-caf5abad6e04
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 17647a4e-555f-49c4-ac53-e0a1ea9e5b40 # Contentbuilder CTA (Single)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f7f6839-1be4-434b-b363-821879c54f91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aa25d54-3048-44b1-a43e-60454557a95b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebeecdff-5e28-44c3-8233-ca59e850eb04
        userCondition: null
handle: callToAction
hasTitleField: false
icon: link
name: 'Call To Action'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
