fieldLayouts:
  8dcbda1a-c185-4163-aeaf-796a6cda5b36:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3737b14d-44ab-44b0-9135-978a9fbb8457
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4afb8c9a-287a-4d02-902f-dcbc0616c905
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ed9fdac-8778-4721-95b7-e6dd91159bc8
            userCondition: null
            warning: null
            width: 100
        name: Contact
        uid: 7623ccc0-0b4c-402b-b9b9-e7a2a736dde2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Address & contact information'
            type: craft\fieldlayoutelements\Heading
            uid: deebe8bb-9e47-4e20-bd51-db7780544027
            userCondition: null
          -
            elementCondition: null
            fieldUid: 6ca94949-c3f4-465d-88c7-3d4736d97ed4 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84b24ede-e5eb-4e23-b005-016b7ae6b8a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 072209d1-1c68-4ee5-9a66-a209b518da6d # Mail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d99460c5-6a52-491f-8cdf-ab08063d28cd
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e48813cd-24dc-4b06-a97d-2a95520dcc24 # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 642d630a-c990-47fc-b308-11d6531d36eb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Social Media'
            type: craft\fieldlayoutelements\Heading
            uid: 5b7c5c9f-3ad7-41dc-a8bf-1d026e89882b
            userCondition: null
          -
            elementCondition: null
            fieldUid: f694fce1-48ca-4bfe-9fba-196195547a36 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e523036d-68e2-4a23-a1a9-88949fdca291
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e4b3bb0-26e4-47d2-9445-54401a221c63 # X (Twitter)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b836a3e-18e2-4f60-b69b-cc4fb47b0577
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce1fab3c-0b02-49d8-8d8f-1bab2d7c05e2 # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3d6bd3c-f471-4dd1-a948-727d55cba323
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bc4b9f2-7fc6-48b0-a3df-8e9c061a70c6 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88b90b92-92d4-4adc-9335-eea6f04cf490
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6221c006-75b9-4fa5-a352-4cd4317fb5d7 # Youtube
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ae6b924-eb5b-41eb-858b-b86075ba074e
            userCondition: null
            warning: null
            width: 100
        name: 'General info'
        uid: 7c7c7a15-293f-4c7f-9b41-c68ae7e3af8f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcd8f070-8f6b-4ed7-b0a9-ee860c739ae8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 462fc961-ddec-4f6d-9764-2d0ee19c129c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc327c80-6c47-4689-b193-d6fae7f28b35
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: a67e40fc-5230-4085-b07d-3544e2e5ac38
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a474f79e-0d0a-418c-8779-deba5068d412
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b7d16813-7c6c-4430-9581-502209fcbd21
        userCondition: null
handle: contact
hasTitleField: true
name: Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
