color: blue
fieldLayouts:
  b99f4595-d28c-453a-86c2-db4f82eaf870:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1a625f9e-08d0-4a20-8ad2-f1ab0f487b4b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7a7c850-a9e8-4903-935d-be1ff16aaf92
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4e0e49a-bcd4-4d67-80ad-09ea0d807bd8 # CK Editor - Table
            handle: table
            includeInCards: false
            instructions: null
            label: Table
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6dc8760-1fb1-431b-a419-4d199757ca92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ecee8ded-a8fe-4ff9-b68a-a9abb32d3a76
        userCondition: null
handle: customTable
hasTitleField: false
icon: table
name: 'Custom Table'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
