color: blue
fieldLayouts:
  f1fdccc1-a100-4e49-a3a9-2b6a15570449:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-12T15:46:08+00:00'
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 821b8296-27bd-45da-a1b2-792dca9cc68b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T15:46:08+00:00'
            elementCondition: null
            fieldUid: 1ea43556-c1c6-4ae7-9c49-48498a82f797 # CK Editor - Extended
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c81ea90-7341-4601-9414-aeaf365cdf5b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T15:53:53+00:00'
            elementCondition: null
            fieldUid: 0ae7aca0-8626-4182-9eec-e9aed42c8f8f # Title + Text
            handle: faqBlock
            includeInCards: false
            instructions: null
            label: FAQ
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ce0dce3-54f7-4ec3-9571-c36709697230
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-12T16:04:39+00:00'
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed0a85ab-8479-4e9c-a53f-1684f9caa25c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 20bd75f2-c913-4897-a48b-20b330b0a821
        userCondition: null
handle: faq
hasTitleField: false
icon: lightbulb
name: FAQ
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
