fieldLayouts:
  067900cf-e356-4104-9389-f5f08ef63d0d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ae32d438-bd75-4328-84a5-e4c594cac7db
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24bbf5b9-9ab8-436a-b78d-0c5e4c63b940
            warning: null
            width: 100
        name: Content
        uid: c755ce33-5fa7-4c39-9aaa-fac2f3e9f22f
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9bfb74d-bec1-4177-9e96-5d8b1d2a467d
            warning: null
            width: 100
        name: SEO
        uid: d34ac62a-0ee1-4b0e-a64d-ae5bb64ee034
handle: forgotPasswordConfirmation
hasTitleField: true
name: 'Forgot Password Confirmation'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
