color: blue
fieldLayouts:
  9334ab5d-2a5e-48de-8e2b-f9473c1d7ffb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be9b93fc-3d50-482a-b7e9-cf1810330269
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Contentbuilder Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cff3141e-84b2-4e71-92eb-5dfc0c3ddd17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b866ebd2-431e-47e9-8db0-97c56606cb70 # Text - Contentbuilder Body Standard
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4ed4f28-d68c-466a-960b-e7a6ded6428d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74a30650-eb90-462f-a104-de1d41ac8221
            handle: null
            includeInCards: false
            instructions: null
            label: Form
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d82ff4e9-a339-4dc7-993a-33ddbc7770e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88b93bad-87ed-4279-b1c7-fc507243b1c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93748cb1-718c-4f6b-bf7f-2905cce71126
        userCondition: null
handle: form
hasTitleField: false
icon: input-text
name: Form
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
