color: null
fieldLayouts:
  63a576be-e5a1-42a0-8eda-4165892703fd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2184d090-d3e1-413b-8d21-b537c5141ef8
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2d6ef90-7210-48ad-a51c-200fb5b1e1e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2cda3ff-d4de-4c81-a8c2-944f82c303db
            handle: null
            includeInCards: true
            instructions: null
            label: Title
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 003f98c4-765a-40ca-a3e3-54a939e9dd59
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d04eb799-5eb6-46db-92f8-88c4e6b8812e
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b54acd3-0bf2-44fa-83a9-bbf84c59e917
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f936530d-29a5-4460-9ccd-b586bfb25329
            handle: null
            includeInCards: false
            instructions: null
            label: 'Call to actions'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f10f7bbc-a341-46d7-9548-1c3111ff6e01
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0a1f43c-d76e-40d3-9b39-e2a0e2021a72
        userCondition: null
handle: heroBlock
hasTitleField: false
icon: null
name: 'Hero Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
