color: null
fieldLayouts:
  3ae7bc1a-3549-4cf7-b582-b14850d82009:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fa60ffae-97ec-4cfa-9978-ec0a05bceef0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37471b2c-6c44-4b1a-bc50-3788e9de05d5 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e69dbd6f-5f31-42bb-8dc6-15295794e1e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26edc70e-aab7-4107-aa16-bd279d4453ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27c4013a-a736-44bd-ac5a-5ba7b8f10637
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3203a502-33ac-4cdd-9139-006850d5627e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2edfc9a6-55ff-4830-ab05-a42e2984a3b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04167f07-ca1f-4dfa-84e3-6b2217e7a2a6
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 470937a0-a5e1-4378-8cd3-7e29104d95b3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33b01e08-9aea-4f24-b03e-6654d5832e27
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 59631741-b006-4665-a50b-601e21c7208c
        userCondition: null
handle: home
hasTitleField: false
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
