fieldLayouts:
  1bfb15de-84e7-42f7-b958-7aaaebfef219:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b64f4137-21d9-4b41-8196-3ae5f44455de
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 8ff8437a-a38f-47f0-b489-1701614eec3f # Header image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 490309e7-ecdb-4c8f-8ed2-27687c571112
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac415f57-3772-45b6-96e5-876e4bf485d9
            userCondition: null
            warning: null
            width: 100
        name: Common
        uid: a5004c88-153b-4815-8b1c-00a56e996b62
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cf2bb60-3914-4982-9eca-f6c813198bcc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e2ee7ec-27f8-45a9-9fbb-e209ee4a5005
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 828ba4f5-988d-4a66-8034-6a9b825645ee
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 154d9d1a-e325-4436-a9db-5143867fab0a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1236872c-7e0b-4eef-abf0-a0ec7b3a3f82
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2e1ee6dc-6a33-4460-a411-7b301e05339f
        userCondition: null
handle: newsOverview
hasTitleField: true
name: 'News Overview'
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
