fieldLayouts:
  e649780e-8bf9-4c9b-82f7-f60db1204d40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ead2c767-fdc3-46c0-bcfe-cd972d8c1528
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8ff8437a-a38f-47f0-b489-1701614eec3f # Header image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 818d1189-bba4-484d-9a18-86a44381c99d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b097df2-956c-43f7-9004-c4fe3547855b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 79e512cf-cb81-4eb7-8e3c-d8bdcbfaf463
            userCondition: null
          -
            elementCondition: null
            fieldUid: 56d715d0-6a9d-4562-9c66-e5b4caad7f44 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e301bd2-4f48-4d65-b2cf-0a67c5e73199
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7f05fcd-6b9c-44dd-baee-f3e9cd0c47ac # News Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09f68857-ed8b-4730-be3d-efd87b7b4ceb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e191a2d3-f251-4cf4-b1de-1262c64534a6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a2bad07-8d89-4689-b0bf-774eed764660 # Overview title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 580d68a6-fe4d-4f8f-a592-6ad57e55a870
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38 # Overview description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c1ea5f7-3de4-4fb8-b7b1-e04626a4c9a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15ed2b72-8955-4cec-93f8-9736a9e50e80 # Overview image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c22f70d-7c04-41c8-9d18-16c6c67d4b70
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 8e03f7a2-91ea-4706-8af9-9bb0746169c9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62a037ab-c0e7-49cf-a558-454d925261bb
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 3d4120a2-2c23-4ad7-b3b7-ee94c4cc5953
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 82edb6db-a497-4e37-8c25-5d4d210f0c81 # Search keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1043e77a-e028-4673-b333-35d1bd466c2e
            userCondition: null
            warning: null
            width: 100
        name: 'Site search'
        uid: 09220906-7404-4d8e-92f1-5f70d33b88f1
        userCondition: null
handle: news
hasTitleField: true
name: News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
