color: null
fieldLayouts:
  0f0db14f-2f40-48e1-853e-ba4ea386b28f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 91b537c7-dec5-49dc-9e5a-b3ddce99c66d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 933f619e-82e4-4b3d-a27f-9d7d9cce42b8
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbc1da18-20d8-4498-b092-47081ee7ae11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a0dd6a8-9ebb-44f8-a62a-03f12bf2a504
            handle: null
            includeInCards: false
            instructions: null
            label: Author
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8eb0aca1-2882-4c08-b7ee-5ac875f9ce84
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 44549f86-4264-4c94-964c-a927c53c2a38
            handle: null
            includeInCards: false
            instructions: null
            label: 'Author Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cacc93e6-e85e-410b-b9c4-a9e85962e836
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c87ed224-8384-4f52-b68e-25ee0f423d52 # Contentbuilder CTA (Double)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 520b48d3-fa08-4251-93a5-d7af7e514323
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7bfca6b9-10b5-45cf-a470-29d85f876c61
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14a7aa7f-00ce-4c5e-83c8-26626d93de0a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87b0e6d6-6529-46f2-b359-dd62254ea435
        userCondition: null
handle: quote
hasTitleField: false
icon: ''
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
