color: blue
fieldLayouts:
  0f0db14f-2f40-48e1-853e-ba4ea386b28f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-27T13:49:58+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 91b537c7-dec5-49dc-9e5a-b3ddce99c66d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 7d5a93a5-4324-462a-9dad-375cb5172cce # Text - Contentbuilder Body Simple
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1a70797-402b-4824-9df9-1f9fc97b2694
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 9a0dd6a8-9ebb-44f8-a62a-03f12bf2a504 # Content Builder - Quote - Author
            handle: null
            includeInCards: false
            instructions: null
            label: Author
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8eb0aca1-2882-4c08-b7ee-5ac875f9ce84
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 44549f86-4264-4c94-964c-a927c53c2a38 # Content Builder - Quote - Author Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Author Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cacc93e6-e85e-410b-b9c4-a9e85962e836
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: c87ed224-8384-4f52-b68e-25ee0f423d52 # Contentbuilder CTA (Double)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 520b48d3-fa08-4251-93a5-d7af7e514323
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7596b9b-b65e-43e4-9cc4-f72d859d0351
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87b0e6d6-6529-46f2-b359-dd62254ea435
        userCondition: null
handle: quote
hasTitleField: false
icon: quote-right
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
