fieldLayouts:
  e06b82b0-43b0-4483-a082-511b04afce72:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f00cf962-2ab7-4f99-b3ed-2838c886daab
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6d3600a-70d0-406f-8283-ec4deee10040
            warning: null
            width: 100
        name: Content
        uid: 8a3768f4-c112-4a8c-a977-39064aa0c8ca
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a8da798-5a12-408c-9ea9-7c050ef371f9
            warning: null
            width: 100
        name: SEO
        uid: 2079e7b5-b97f-46c4-a052-d83c6c260e20
handle: setPasswordConfirmation
hasTitleField: true
name: 'Set Password Confirmation'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
