fieldLayouts:
  f84d33ce-0718-49b0-9cc6-b85210dcdabb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e647faa3-934a-40d5-8783-a7da0db47ab2
            warning: null
            width: 100
          -
            fieldUid: b5de6dcf-80e6-48e2-b846-0dab7f35c4c8 # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14c560fa-184a-4944-b16a-82c03aaf1969
            warning: null
            width: 100
        name: Content
        uid: 6b6c9154-76a6-4562-8f1a-ae5c3382ad7c
      -
        elements:
          -
            fieldUid: 685530fc-e1f1-4be1-813b-ebf9ac3aa108 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbd36d19-a422-4db8-991a-cc84c1ba42bb
            warning: null
            width: 100
        name: SEO
        uid: 18196894-67ca-4183-8e53-2a6a25fd3266
handle: setPassword
hasTitleField: true
name: 'Set Password'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
