fieldLayouts:
  2c85b916-cde3-4f4a-a45b-7df51bfd7a5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d57dec6-c99a-49d1-9d97-3017206fc28a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc4c53fd-5da6-434f-8b07-8bcc6776952a
        userCondition: null
handle: siteSettings
hasTitleField: false
name: 'Site Settings'
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
