color: null
fieldLayouts:
  2c85b916-cde3-4f4a-a45b-7df51bfd7a5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-27T13:49:58+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6fdc728e-cb14-44f6-83b7-d2b7243a3910
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d57dec6-c99a-49d1-9d97-3017206fc28a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc4c53fd-5da6-434f-8b07-8bcc6776952a
        userCondition: null
handle: siteSettings
hasTitleField: false
icon: gear
name: 'Site Settings'
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
