color: null
fieldLayouts:
  f4023492-353e-4a86-9695-455793644dc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69e397e5-732d-4e21-8924-bc5b3943f7dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a9703c9-1eb8-4b3a-94e1-1386e5b24f2a
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc1db95c-60f0-4911-8c01-fbd89b5f9a06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b8bf7de4-8025-4da7-9040-09ec8b731016
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05aa0d0e-b0b6-4161-a302-d52aa0e73032
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c87ed224-8384-4f52-b68e-25ee0f423d52 # Contentbuilder CTA (Double)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d051ae6-caac-471e-a524-898370a94f26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f21594e6-d83e-4047-a36c-0d6b709719e1
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed69e655-73d9-4f2b-94a0-2275e9b4faf8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40e14f90-0640-452d-9c8a-9f30f73bacbb
            handle: position
            includeInCards: false
            instructions: null
            label: 'Image position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e11cb59-1985-4f62-8da1-4c8694b813fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd732ee5-59bb-41a5-81e1-b0de29ca7146
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ed3a959-a53c-497c-8838-852a96e2c278
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3cac461-fd7a-4f9a-8486-520f99041b3f
        userCondition: null
handle: textImage
hasTitleField: false
icon: ''
name: 'Text (+ Image)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
