color: blue
fieldLayouts:
  f4023492-353e-4a86-9695-455793644dc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-27T13:49:58+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69e397e5-732d-4e21-8924-bc5b3943f7dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Contentbuilder Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc671e99-b18e-4bf8-87ad-2be57587de6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: a25500cb-7c0d-474d-8ee0-757e3d200063 # Text - Contentbuilder Body Extended
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27ef5ef9-5e24-49b1-a0b2-cf30f86d4ff7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: c87ed224-8384-4f52-b68e-25ee0f423d52 # Contentbuilder CTA (Double)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d051ae6-caac-471e-a524-898370a94f26
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: f21594e6-d83e-4047-a36c-0d6b709719e1 # Content Builder - Text (+ Image) - Image
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed69e655-73d9-4f2b-94a0-2275e9b4faf8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: f21594e6-d83e-4047-a36c-0d6b709719e1 # Content Builder - Text (+ Image) - Image
                  layoutElementUid: ed69e655-73d9-4f2b-94a0-2275e9b4faf8
                  operator: notempty
                  uid: d1f35874-2cea-4b59-9cc5-aac8619d3a69
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 8c9b2c5d-02c2-4105-83ed-93563621e752 # Position Left/Right
            handle: position
            includeInCards: false
            instructions: null
            label: 'Image position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aea3eb8a-15e5-4db6-bc7d-343295ff324a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 872eeeca-445c-4f8f-a3f9-6ef0c2e3af98
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3cac461-fd7a-4f9a-8486-520f99041b3f
        userCondition: null
handle: textImage
hasTitleField: false
icon: text
name: 'Text (+ Image)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
