color: blue
fieldLayouts:
  86d679f2-c66c-4cad-a0cc-63b8753b55a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-27T13:49:58+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7b60618d-d9d5-41c4-ade2-d51291d7496a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Contentbuilder Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c805501d-038d-4926-b2d9-1c26513c0568
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: a25500cb-7c0d-474d-8ee0-757e3d200063 # Text - Contentbuilder Body Extended
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e1cf21d-f658-4bc0-9c77-2bcc87240e89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: c87ed224-8384-4f52-b68e-25ee0f423d52 # Contentbuilder CTA (Double)
            handle: cta
            includeInCards: false
            instructions: null
            label: 'Call to action'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce11868c-4ce8-4e9c-8a7c-4776531b3000
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 2561c4fb-34b5-49e6-ade6-f774411e48ba # Content Builder - Text + Video - Video
            handle: video
            includeInCards: false
            instructions: null
            label: Video
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3b691ab-3aba-42aa-9b69-08b6498a0827
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 896816a1-5444-4e1b-b74c-efbac472953c # Content Builder - Text + Video - Placeholder Image
            handle: placeholderImage
            includeInCards: false
            instructions: null
            label: 'Placeholder Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ada65645-8cc4-4f63-a6cf-2c60df1e7396
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 8c9b2c5d-02c2-4105-83ed-93563621e752 # Position Left/Right
            handle: position
            includeInCards: false
            instructions: null
            label: 'Video position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33483741-3e6c-4747-bc42-65fd061f852c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: d364a1b7-6f05-47e2-a5b3-e9f38308473c # Text - Caption Text
            handle: videoCaption
            includeInCards: false
            instructions: null
            label: 'Video Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1281e54a-1dce-496a-9275-4fa521679f8e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T13:49:58+02:00'
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2f91d1b-a5bd-471e-9fe1-0b54cba21883
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dba25c67-8336-4776-bb85-63e3fffb4f1e
        userCondition: null
handle: textVideo
hasTitleField: false
icon: video
name: 'Text + Video'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
