color: null
fieldLayouts:
  8e0153f8-35f6-4a49-bc77-316bc5dce081:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24983cba-9d55-413d-80dc-0374abd19ec0
            handle: null
            includeInCards: false
            instructions: null
            label: 'Title Column 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1e3e29f-0360-4cf5-9e9c-185e52b35ec3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1cd3558-d939-48d0-8628-239236ff699c
            handle: null
            includeInCards: true
            instructions: null
            label: 'Text Column 1'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8066edd1-fae1-4876-b905-cecb2c112d8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bde7c3e4-1530-4cdf-94a4-6ac068e88c8a
            handle: null
            includeInCards: false
            instructions: null
            label: 'CTA Column 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a27db994-44cd-49ce-9e65-16ce6ec8334a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e73dd38a-5d76-40ba-99eb-25ee65bf7ab5
            handle: null
            includeInCards: false
            instructions: null
            label: 'Title Column 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12b922f4-dd7e-425b-a3ba-137fc623d829
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2d7684e-6737-4123-ad14-2c4e4221bbdd
            handle: null
            includeInCards: false
            instructions: null
            label: 'Text Column 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59368b27-46f3-4c5b-93b7-9e5bf5641ce9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 84a6a70f-85ce-43a5-ad74-738a0cbea388
            handle: null
            includeInCards: false
            instructions: null
            label: 'CTA Column 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3461e881-b526-426b-be4a-727375056942
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e5318bd-23e0-4319-8f7c-3f38350d8764
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c08b825-8341-4ca0-a415-67be5bbd04ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a9d5fcb-7371-45df-b9f8-0a603830f3a3
        userCondition: null
handle: textTwoColumns
hasTitleField: false
icon: null
name: 'Text (2 columns)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
