color: null
fieldLayouts:
  fad89760-e632-45a2-981a-735d7a5e2fe7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-12T15:52:15+00:00'
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99ac29a6-3470-4167-95c4-376c04d46e83
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T09:46:19+00:00'
            elementCondition: null
            fieldUid: bbb6f7a2-b1e0-45d0-8a0d-805501952c5f # CK Editor - Extended without H3
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ad80e2c-6bac-40fe-a7b3-9a5d0714c790
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ea7b16c-adf3-45f5-81de-c2c079451233
        userCondition: null
handle: titleText
hasTitleField: false
icon: null
name: 'Title + Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
