color: blue
fieldLayouts:
  4bb37325-4657-4b4b-a37d-a9601263cf72:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eddc6813-b8b9-40b5-b2c5-d1c6d9582399
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a
            handle: null
            includeInCards: true
            instructions: null
            label: Video
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10b5c1ef-5a1d-4b4f-90ca-41388b1bc2d1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 724561c2-845a-427f-b005-e0c2a35e0112
            handle: null
            includeInCards: false
            instructions: null
            label: 'Placeholder Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84cf6f5-a37f-4a41-8908-4157a510c99d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d364a1b7-6f05-47e2-a5b3-e9f38308473c # Text - Caption Text
            handle: videoCaption
            includeInCards: false
            instructions: null
            label: 'Video caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19a6c41e-6804-4c85-9e8a-21d0789c8c2c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Content Builder  Background Color
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e587b459-84d1-48e7-bc62-527eb0dd6923
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b44f4cf-c6f3-495e-b01a-3cb36749abfd
        userCondition: null
handle: video
hasTitleField: false
icon: video
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
