color: null
fieldLayouts:
  4bb37325-4657-4b4b-a37d-a9601263cf72:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d66ffcef-8ccc-4e89-9e36-bce49e0dd17a
            handle: null
            includeInCards: true
            instructions: null
            label: Video
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10b5c1ef-5a1d-4b4f-90ca-41388b1bc2d1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 724561c2-845a-427f-b005-e0c2a35e0112
            handle: null
            includeInCards: false
            instructions: null
            label: 'Placeholder Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b84cf6f5-a37f-4a41-8908-4157a510c99d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fca40313-aa0d-4206-a530-c638a5166f69
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee4947c6-1e36-4c0a-9f92-995d187c1983
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ae5f2b18-f88e-4521-a729-d5fccff56993
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cf136e3-1af6-43c5-bcd3-2d6cf2878c1c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 1b44f4cf-c6f3-495e-b01a-3cb36749abfd
        userCondition: null
handle: video
hasTitleField: false
icon: null
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
