altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  8985b5d5-d4d2-4e77-a044-b0cba33552b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: warning
            tip: 'Files uploaded in this folder are public by default, meaning anyone can access the files. Contact us if you would like to store sensitive data in your website.'
            type: craft\fieldlayoutelements\Tip
            uid: d6559608-cb65-4dba-b7d7-5b5a1f702eef
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 6e85e607-ddd1-4b5f-b900-19426217956d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 613a44f5-6a37-4c31-9640-88cb393cb476
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39f07216-d49a-4917-b05e-bec26f425843 # Caption
            handle: imageCaption
            includeInCards: true
            instructions: 'This will most likely be visible below the image'
            label: 'Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72d09997-657f-46cc-ab0b-5b48e28bdbfb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcf87482-b5f3-4be6-9a63-153f0458466b # Image Copyright
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e9dc273-861f-4698-8e81-099c5675056a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a25f3e9-a180-4a29-aa41-8721fbf815b9 # Optimized Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f9080c9-bf9d-4084-b710-ceef5826f05b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60b48ff5-1ab2-471b-8592-cdc623e0882c # Optimized Text Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 695bcd34-7f82-4894-8f74-8c6e802d8ed3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0207f1a0-8ec0-4b87-9197-c1d5a9a7b61d # Optimized Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dc766b5-69d9-426f-8ed2-18b0dd6971c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 197566c6-94bb-4e67-86d7-8945f2589a1d # Optimized Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e86b8ca-aa8b-4838-a936-f06aa938331f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54f7b51a-036d-4e8c-a19e-ee62929e30b6
        userCondition: null
fs: files
handle: publicFiles
name: 'Public Files'
sortOrder: 0
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
