altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  8985b5d5-d4d2-4e77-a044-b0cba33552b7:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:72d09997-657f-46cc-ab0b-5b48e28bdbfb'
      - 'layoutElement:1e9dc273-861f-4698-8e81-099c5675056a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-14T06:42:46+00:00'
            dismissible: false
            elementCondition: null
            style: warning
            tip: 'Files uploaded in this folder are public by default, meaning anyone can access the files. Contact us if you would like to store sensitive data in your website.'
            type: craft\fieldlayoutelements\Tip
            uid: d6559608-cb65-4dba-b7d7-5b5a1f702eef
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T06:42:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 6e85e607-ddd1-4b5f-b900-19426217956d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-07-10T07:39:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: 'Alternative text is a textual substitute for images. Screen readers announce the alternative text, but it is also displayed if the image fails to load. Search engines also use alternative text and factor it into their assessment of the page purpose. Use the alternative text to describe what the image means within its context, not what it depicts. Leave empty if the image serves a purely ornamental or decorative purpose.'
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 98be8a9f-0c1f-4fe2-8789-fdf33a33024d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T06:42:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 39f07216-d49a-4917-b05e-bec26f425843 # Caption
            handle: imageCaption
            includeInCards: true
            instructions: 'This will most likely be visible below the image'
            label: 'Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72d09997-657f-46cc-ab0b-5b48e28bdbfb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T06:42:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bcf87482-b5f3-4be6-9a63-153f0458466b # Image Copyright
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e9dc273-861f-4698-8e81-099c5675056a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54f7b51a-036d-4e8c-a19e-ee62929e30b6
        userCondition: null
fs: files
handle: publicFiles
name: 'Public Files'
sortOrder: 0
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
