columnSuffix: null
handle: blockTitle4
instructions: 'Add an optional title to the block'
name: 'Content Builder - Text (+ Image) - Title'
searchable: true
settings:
  someAttribute: null
translationKeyFormat: null
translationMethod: site
type: modules\statik\fields\AnchorLink
