columnSuffix: null
handle: entries
instructions: 'Select entries  to display in this overview'
name: 'Content Builder - Overview - Entries'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: true
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
