columnSuffix: xbqglaie
handle: imageWidth
instructions: null
name: 'Content Builder - Image - Image width'
searchable: false
settings:
  default: ''
  options:
    __assoc__:
      -
        - 1/6
        - ''
      -
        - 1/5
        - ''
      -
        - 1/4
        - '1'
      -
        - 1/3
        - '1'
      -
        - 2/5
        - ''
      -
        - 1/2
        - '1'
      -
        - 3/5
        - ''
      -
        - 2/3
        - ''
      -
        - 3/4
        - ''
      -
        - 4/5
        - ''
      -
        - 5/6
        - ''
      -
        - full
        - '1'
translationKeyFormat: null
translationMethod: none
type: rias\widthfieldtype\fields\Width
