columnSuffix: null
contentColumnType: text
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: imageCopyright
instructions: 'Credit of the image'
name: 'Image Copyright'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
