columnSuffix: vwktiheg
handle: imagePosition
instructions: null
name: 'Content Builder - Image - Image position'
searchable: false
settings:
  default: center
  options:
    __assoc__:
      -
        - left
        - '1'
      -
        - center
        - '1'
      -
        - right
        - '1'
      -
        - full
        - ''
      -
        - drop-left
        - ''
      -
        - drop-right
        - ''
translationKeyFormat: null
translationMethod: none
type: rias\positionfieldtype\fields\Position
