contentColumnType: string
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: mail
instructions: ''
name: Mail
searchable: true
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
