columnSuffix: null
contentColumnType: text
handle: optimizedContent
instructions: 'Optimized images for the content builder.'
name: 'Optimized Content'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: false
  displayOptimizedImageVariants: false
  fieldVolumeSettings:
    __assoc__:
      -
        - publicFiles
        - '*'
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '820'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '660'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '375'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
