columnSuffix: null
contentColumnType: text
handle: optimizedOverview
instructions: 'Optimized images for overview items.'
name: 'Optimized Overview'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: false
  displayOptimizedImageVariants: false
  fieldVolumeSettings:
    __assoc__:
      -
        - publicFiles
        - '*'
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '660'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '440'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '375'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
