columnSuffix: btcjcicd
contentColumnType: text
fieldGroup: 2c770290-8edc-4f26-b846-6d99d36d7844 # Common
handle: phone
instructions: ''
name: Phone
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
