columnSuffix: null
handle: plainTextTranslatable
instructions: null
name: 'Plain Text (Translatable)'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
