columnSuffix: null
handle: textColumn2
instructions: 'Type the second column text here'
name: 'Content Builder - Text (2 columns) - Text Column 2'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 25f93ead-d3f6-4049-ba98-6378754f4289 # Extended
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
