columnSuffix: null
handle: text2
instructions: 'Type your quote here'
name: 'Content Builder - Quote - Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 131a4f6d-f00f-4238-b846-dd504bf669fe # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
