defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9f39fdda-793c-4506-9dd4-e764d46cad28 # Contentbuilder Page
handle: cookiePolicy
maxAuthors: 1
name: 'Cookie policy'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: '{slug}'
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: '{slug}'
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: '{slug}'
type: single
