defaultPlacement: end
enableVersioning: true
handle: cookiePolicy
name: 'Cookie policy'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # fdsa
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: cookies
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: cookies
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_contentPage
    uriFormat: cookies
type: single
