defaultPlacement: end
enableVersioning: true
handle: forgotPassword
name: 'Forgot password'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # fdsa
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_passwordRequestReset.twig
    uriFormat: wachtwoord-vergeten
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_passwordRequestReset.twig
    uriFormat: forgot-pasword
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_passwordRequestReset.twig
    uriFormat: mot-de-passe-oublie
type: single
