defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2a768305-5971-43c0-a2f4-415e648c6a45 # Default
handle: newsCategories
name: 'News categories'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 3
  uid: b7f87597-c391-468e-ab5d-ce055d8b15b1
type: structure
