defaultPlacement: end
enableVersioning: true
entryTypes:
  - 109f5d44-e366-49e7-826d-6b13de779861 # News
handle: news
maxAuthors: 1
name: 'News items'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: false
    hasUrls: true
    template: _site/_news/_entry
    uriFormat: "{{craft.entries.section('newsOverview').status(null).one().slug}}/{slug}"
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: false
    hasUrls: true
    template: _site/_news/_entry
    uriFormat: "{{craft.entries.section('newsOverview').status(null).one().slug}}/{slug}"
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: false
    hasUrls: true
    template: _site/_news/_entry
    uriFormat: "{{craft.entries.section('newsOverview').status(null).one().slug}}/{slug}"
type: channel
