defaultPlacement: end
enableVersioning: true
entryTypes:
  - be8c0ed1-8b8b-4cfe-bcca-d4f54be7bfff # Page not found
handle: pageNotFound
name: 'Page not found'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
type: single
