enableVersioning: true
handle: registrationCompleted
name: 'Registration completed'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: _account/_registration-completed
    uriFormat: registratie-voltooid
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _account/_registration-completed
    uriFormat: registration-completed
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _account/_registration-completed
    uriFormat: inscription-terminee
type: single
