defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b13fc4bd-af47-4f5c-b349-05e9e24dfecc # Search results
handle: searchResults
maxAuthors: 1
name: 'Search results'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: _site/_searchResults.twig
    uriFormat: search-results
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_searchResults.twig
    uriFormat: search-results
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_searchResults.twig
    uriFormat: search-results
type: single
