defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8f0da589-76b2-4663-9209-ba978821ca83 # Set Password Confirmation
handle: setPasswordConfirmation
name: 'Set Password Confirmation'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_passwordSetConfirmation.twig
    uriFormat: wachtwoord-ingesteld
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_passwordSetConfirmation.twig
    uriFormat: password-set
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_passwordSetConfirmation.twig
    uriFormat: mot-de-passe-ensemble
type: single
