defaultPlacement: end
enableVersioning: true
entryTypes:
  - 75c71ec6-7c59-460d-bac3-80ae2ee887a5 # Site Settings
handle: siteSettings
name: 'Site Settings'
propagationMethod: all
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
